### ISSUE TITLE
2.5.0で再生出来ない状態

### ISSUE THREAD

**Issue by kagura-y** [SSW-SCIENTIFIC/NNDD#1]
2chからです。「市場情報を取得しています… 成功」まで表示されて止まります。
ライブラリにある動画は再生出来ますが、
市場タブに「市場情報が存在しないか、市場情報の解析に失敗しました。」と表示されてます。
投稿者タブの投稿者名：の後ろが何も表示されていません。
以下ログから抜粋

20170502115022:アプリケーションの起動 - NNDD
	***** NNDDはMineAppProjectが作成しています。 *****
	NNDDプロジェクト	http://sourceforge.jp/projects/nndd/
	MineAppProjectブログ	http://d.hatena.ne.jp/MineAP/
	*********************************************
	AIRランタイムバージョン:25.0.0.134
	FlashPlayerバージョン:WIN 25,0,0,127
	デバッガバージョン:false
	プレイヤータイプ:Desktop
	オペレーティングシステム:Windows 8
	ネイティブプロセスAPIサポート:true
	暗号化された保存領域のサポート:true
	最高レベルIDC:5.1

	NNDDは以下のライブラリを使用しています。
	・NativeApplicationUpdater - Apache License V2.0 ( http://code.google.com/p/nativeapplicationupdater/ )
	・airhttpd - MIT License ( http://code.google.com/p/airhttpd/ )
	・nicovideo4as - MIT/X Consortium License ( http://sourceforge.jp/projects/nndd/ )

20170502115022:	設定情報の読み込み:D:\Users\*****\AppData\Roaming\org.mineap.nndd\Local Store\config.xml
20170502115022:	データベースとのコネクションを切断(D:\kagurayuuki\Documents\NNDD\system\library.db)
20170502115022:	データベースとのコネクションを切断(D:\Videos\NNDD\system\library.db)
20170502115022:	データベースへコネクションを確立(D:\Videos\NNDD\system\library.db):true
20170502115022:	データベースとのコネクションを切断(D:\Videos\NNDD\system\library.db)
20170502115022:	データベースへコネクションを確立(D:\Videos\NNDD\system\library.db):true

（マイリストチェックのログ）

20170502115344:	NGリストの読み込み完了:D:\Videos\NNDD\system\ngList.xml
20170502115344:	***ストリーミング再生の準備***
20170502115344:	LoginStart:sm31122321
20170502115344:	動画を再生:http://www.nicovideo.jp/watch/sm31122321
20170502115344:		LoginSuccess:sm31122321:null
20170502115344:	WatchStart:sm31122321
20170502115344:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://www.nicovideo.jp/watch/sm31122321"]
20170502115344:		WatchSuccess:sm31122321:null
20170502115344:	ThumbInfoGetStart:sm31122321
20170502115344:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://ext.nicovideo.jp/api/getthumbinfo/sm31122321"]
20170502115344:		ThumbInfoGetSuccess:D:\Videos\NNDD\system\temp\nndd[ThumbInfo].xml
20170502115344:	ThumbImgGetStart:sm31122321
20170502115344:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://tn-skr2.smilevideo.jp/smile?i=31122321"]
20170502115344:		ThumbImgGetSuccess:D:\Videos\NNDD\system\temp\nndd[ThumbImg].jpeg
20170502115344:	GetFlvAccessStart:sm31122321(sm31122321)
20170502115345:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://flapi.nicovideo.jp/api/getflv/sm31122321?"]
20170502115345:		GetFlvAccessSuccess:sm31122321:【オーイシマサヨシ】ようこそジャパリパークへ(ニコニコ超会議2017) - [sm31122321]
20170502115345:	CommentGetStart:sm31122321
20170502115345:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://nmsg.nicovideo.jp/api/"]
20170502115345:		CommentGetSuccess:D:\Videos\NNDD\system\temp\nndd.xml
20170502115345:	OwnerCommentGetStart:sm31122321
20170502115345:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://nmsg.nicovideo.jp/api/"]
20170502115345:		OwnerCommentGetSuccess:D:\Videos\NNDD\system\temp\nndd[Owner].xml
20170502115345:	IchibaInfoGetStart:sm31122321
20170502115345:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://ichiba.nicovideo.jp/embed/?v=sm31122321&action=showMain&rev=20100805"]
20170502115345:		IchibaInfoGetSuccess:D:\Videos\NNDD\system\temp\nndd[IchibaInfo].html
20170502115351:	***ライブラリ表示開始***
20170502115351:	ローカルのタグ情報を表示(ディレクトリ指定):D:\Videos\NNDD:60
20170502115351:	動画を表示:D:\Videos\NNDD:15
20170502115351:	***ライブラリ表示完了***

**Comment by SSW-SCIENTIFIC** [comment]
ご報告ありがとうございます。

はっきりとは判断しかねますが, watchページ(http://www.nicovideo.com/watch/[動画ID])を読み込む際にHTML5プレイヤーのページを読んでいるものと思われます。
この辺ちょっと難しくて, watchページをFlash PlayerのデフォルトのUserAgentでロードするとHTML4.01の古めかしいページが, ChromeのようなブラウザのUserAgentならFlash Playerで動画再生するページが読み込まれることまでは確認しましたが, HTML5プレイヤーのページを読む方法がはっきりしません。

とりあえず調査してみますのでお待ちください。

**Comment by kagura-y** [comment]
なるほど、そういうことなら判りやすいです。
ブラウザでの視聴時にhtml5が指定されてると不可ということですね。
flash設定に変えたら見ることが出来ました。

**Comment by SSW-SCIENTIFIC** [comment]
ああ, 確定のようですね。

面倒なことにHTML5プレイヤーモードのときとFlashプレイヤーモードのときでDMCサーバに関するデータの取得方法が異なっていて, 今のところFlashプレイヤーモードを想定して取得しているためにHTML5プレイヤーモードの場合には同情報が取得出来ない状態になっています。
で, エラーチェックきちんとしてないので多分内部でTypeErrorか何か起きて落ちてます。

HTML5プレイヤーモードを明示的に回避するにはCookieにwatch_html5=0を突っ込めばよいということは分かりましたがWindowsでは手動で突っ込めないとActionScriptのAPI Referenceにあったのでどうしようかと思ってます。
というかFlashプレイヤーは一体誰とCookie共有してるんですかね・・・・
