### ISSUE TITLE
起動時に必ず更新通知が表示される(+DLに失敗する動画がある)

### ISSUE THREAD

**Issue by kanedarmj** [SSW-SCIENTIFIC/NNDD#10]
表題のとおりですが、起動時に必ず更新通知が表示されます。
NNDDが更新済みでも表示されます。

環境は以下のとおりです。
　NNDD+DMC 3.0.11
　macOS Sierra(10.12.6)
　一般会員

あとダウンロードできない動画が存在しました。
ttps://www.nicovideo.jp/watch/sm34148161
です。途中までDLされて、最終的に失敗(エラー)になります。ログによるとError #2032のようです。

エラーレポートは初めてなので、過不足等ありましたらすいません。

**Comment by kanedarmj** [comment]
DLできないと報告した動画ですが、再度トライしてみたところ正常終了しました。日を変えて何度実行しても(最低でも5回は試したと思います)失敗したのですが…。すいません。

**Comment by SSW-SCIENTIFIC** [comment]
[update_v2_native.xml](https://github.com/SSW-SCIENTIFIC/NNDD/blob/master/update_v2_native.xml)の更新先バージョン指定のフォーマットが誤っていました(v2.6.0-Betaから)。
修正をpushしましたので更新通知に関しては改善されたのではないかと思います。
