### ISSUE TITLE
"Documents"フォルダ消失時、正常に動作しない

### ISSUE THREAD

**Issue by D-Lumholtzi** [SSW-SCIENTIFIC/NNDD#11]
大変お世話になっております。(平時の感謝も込めまして。)

表題について、割と特殊な問題なので恐縮ですが、
Windowsで設定していた「ドキュメント」フォルダが何らかの経緯で消失した場合、
NNDDフォルダを件の場所と無関係な場所(デスクトップ等)に設定していても
ログイン窓も出ず、ログオフ等のボタンも機能せず、終了もできない状態に
陥ってしまいました。

環境は以下の通りです:
    NNDD+DMC v3.0.12-Beta (, NNDD v2.4.3 ... 本家でも発生を確認)
    Adobe AIR v32.0.0.89
    Windows10 Home 1803
        (「ドキュメント」フォルダは "D:\Users\(ユーザー)\Documents" に設定)
    一般会員

もし差し支え無ければ、動的テスト無しでも
「ドキュメント」フォルダが存在しない場合にも対応していただければと思います。

以上、ご確認のほどよろしくお願いします。

**Comment by SSW-SCIENTIFIC** [comment]
ご報告の問題ですが, Documentsディレクトリが消失しているということはシステムとして正常とは言い難いこと, 問題解決にあたってはDocumentsディレクトリを復旧するのが本筋であること, 同様の問題で困るケースが極めて限られていること, 終了についてもタスクマネージャ等で対応可能なこと, などからWon't fixとします。
