### ISSUE TITLE
ライブラリやプレイリストを並べ替えることができません

### ISSUE THREAD

**Issue by dollvader** [SSW-SCIENTIFIC/NNDD#12]
私の下手な日本語を許してください、翻訳者を使っています。バージョン2.4.1より前では、ライブラリやプレイリストを並べ替えることは可能でしたが、もうそれはできません。意味のない奇妙なパターンで自動的にソートされています。 私は、並べ替えの基準を知りません。 英語と日本語のソートは順不同です。 ソート方法を制御することができません。この問題が自分にだけ当てはまるのかどうかはわかりません。Mac上でv3.0.12-Betaを使っています。添付ファイルをご覧ください。 どうもありがとうございました。
<img width="285" alt="nndd" src="https://user-images.githubusercontent.com/30845243/53458664-a8ea9b00-39fc-11e9-8e40-d453294ce092.png">

**Comment by dollvader** [comment]
さらに、ライブラリ内のファイルフォルダをドラッグすると、他のフォルダと結合することしかできません。 並べ替えるためにフォルダをリストの上下に移動することはできません。 プレイリストエリアでは、リストをまったく移動できません。 ドラッグするとプレイリストのゴースト画像が表示されますが、マウスボタンを放しても何も起こりません。 この情報が役に立つことを願っています。

**Comment by SSW-SCIENTIFIC** [comment]
I have not used playlist and related functions in NNDD, so I do not know where (or on which tab) I can manage (create/add/sort and so on) playlist m3u.
Would you tell me the tab or menu for managing playlist?

**Comment by dollvader** [comment]
On the library tab, in the bottom left corner press the + button. Depending on if the Library or Playlist folder is highlighted, this creates a new library folder or playlist. Renaming the folder/playlist is also done by the rename button in the lower left corner.  You can manage downloaded videos this way. Thank you for your help.

**Comment by SSW-SCIENTIFIC** [comment]
I'm sorry to be late for response.

And, I'm sorry I **won't fix** this issue because I have not rewritten them from ver2.4.4 and functions in library tab have serious performance issue (it blocks NNDD completely during I want only to open that tab) so I feel it is difficult to debug.
