### ISSUE TITLE
AIRランタイムver32.0.0.116に更新すると動画が再生出来ない

### ISSUE THREAD

**Issue by blastdozer1500** [SSW-SCIENTIFIC/NNDD#14]
昨日よりストリーミングでの再生ができなくなりました。

ローカルでの再生もできない状況です。

ストリーミングでの状態としては読み込みができていないように感じられます。
読み込みスピードにマイナスがでたりします（プレミアム会員です）

何か解決策等ありますでしょうか？

**Comment by SSW-SCIENTIFIC** [comment]
@blastdozer さん

現時点で最新版のAIRランタイムであるver.32.0.0.116にはバグがあり, [各種動画が再生出来ないという報告][AIR Bug]が多数上がっています。
ランタイム利用のコードを書く側としては出来ることはないので, バグがないことが確認されているAIRランタイムver.32.0.0.89以前をインストールし直して頂くほかなさそうです。


[AIR Bug]: https://tracker.adobe.com/#/view/AIR-4198798

**Comment by blastdozer1500** [comment]
SSW-SCIENTIFICさん

AIRランタイムを以前のバージョンに戻し、再生できました。
ありがとうございました！

AIRランタイム側に不具合があるとは・・・
