### ISSUE TITLE
Can't open main window メインウィンドウ起動できない

### ISSUE THREAD

**Issue by polujm9** [SSW-SCIENTIFIC/NNDD#18]
I can't open main window now .　　
メインウィンドウ起動できない

But still can open player and watch videos by video ID.　　
プレーヤー正常

I did tried reinstall both NNDD+DMC and Adobe Air but dosen't work.　　
NNDD+DMC4.0.1　と　Adobe Air　再インストール試したけど解決できない

I don't know what happend and how to fix.
助けて

**Comment by SSW-SCIENTIFIC** [comment]
Please paste your environment information in the head of logs (設定 -> ログ), for example:

```log
20210320201204:アプリケーションの起動 - NNDD+DMC
	*****	NNDD+DMCはMineAppProject作成のNNDDをフォークして作成しています。	*****
	NNDD+DMC				 https://github.com/SSW-SCIENTIFIC/NNDD
	問題の報告などはこちらへ	 https://github.com/SSW-SCIENTIFIC/NNDD/issues
	*******************************************************************
	AIRランタイムバージョン:32.0.0.125
	FlashPlayerバージョン:WIN 32,0,0,182
	デバッガバージョン:false
	プレイヤータイプ:Desktop
	オペレーティングシステム:Windows 10
	ネイティブプロセスAPIサポート:true
	暗号化された保存領域のサポート:true
	最高レベルIDC:5.1

	NNDD+DMCは以下のライブラリを使用しています。
	・NativeApplicationUpdater - Apache License 2.0 ( http://code.google.com/p/nativeapplicationupdater/ )
	・airhttpd - MIT License ( http://code.google.com/p/airhttpd/ )
	・nicovideo4as - MIT License ( https://github.com/SSW-SCIENTIFIC/nicovideo4as )
	・Flashls - Mozilla Public License 2.0 ( http://www.flashls.org/ )
```

And if you find error logs in your log output, please paste it.

Further more, tell me what "**Main Window**" means (if it means the window with title "**NNDD+DMC - v4.0.1**", I don't know how you open the player window).

**Comment by polujm9** [comment]
I can't open the "main window"( red in image ) so I can't get  log(設定 -> ログ)
As the image showing the window doesn't show on screen.
But I can open player by right click mouse on system icon and select the green circle option.


![2021-03-20 23_35_42-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/15154432/111875724-29aad400-89d6-11eb-89b4-4a68a2463ae5.png)

**Comment by SSW-SCIENTIFIC** [comment]
Ok, please tell me:

1. Is it occurred from 4.0.0 or 4.0.1? works as expected in 3.1.0?
2. Which version of AIR runtime is installed? It is reported that the AIR from HARMAN won't work properly.
3. If you remove (please back up if needed) directory `%APPDATA%\org.mineap.nndd-dmc` then NNDD+DMC works fine?

**Comment by polujm9** [comment]
1&2. I tried uninstall both  NNDD+DMC and Adobe Air and install 3.1.0 with Adobe Air 32 but still not working.
3.It works fine now after I removed the directory . If I copy config.xml back main sceen wont open again.

Here's my config file(userName tag cleared)(change .xml -> .txt),thank you.
[config.txt](https://github.com/SSW-SCIENTIFIC/NNDD/files/6176714/config.txt)

**Comment by polujm9** [comment]
And here's the log when main window didn't show
found ouput file at ` (video save path)\system\nndd.log
`
```
20210321105155:アプリケーションの起動 - NNDD+DMC
	*****	NNDD+DMCはMineAppProject作成のNNDDをフォークして作成しています。	*****
	NNDD+DMC				 https://github.com/SSW-SCIENTIFIC/NNDD
	問題の報告などはこちらへ	 https://github.com/SSW-SCIENTIFIC/NNDD/issues
	*******************************************************************
	AIRランタイムバージョン:32.0.0.125
	FlashPlayerバージョン:WIN 32,0,0,182
	デバッガバージョン:false
	プレイヤータイプ:Desktop
	オペレーティングシステム:Windows 10
	ネイティブプロセスAPIサポート:true
	暗号化された保存領域のサポート:true
	最高レベルIDC:5.1

	NNDD+DMCは以下のライブラリを使用しています。
	・NativeApplicationUpdater - Apache License 2.0 ( http://code.google.com/p/nativeapplicationupdater/ )
	・airhttpd - MIT License ( http://code.google.com/p/airhttpd/ )
	・nicovideo4as - MIT License ( https://github.com/SSW-SCIENTIFIC/nicovideo4as )
	・Flashls - Mozilla Public License 2.0 ( http://www.flashls.org/ )


20210321105155:	設定情報の読み込み:C:\Users\User\AppData\Roaming\org.mineap.nndd-dmc\Local Store\config.xml
20210321105156:	データベースとのコネクションを切断(C:\Users\User\Documents\NNDD\system\library.db)
20210321105156:	データベースとのコネクションを切断(F:\Videos\niconico\system\library.db)
20210321105156:	データベースへコネクションを確立(F:\Videos\niconico\system\library.db):true

20210321105156:データベースとのコネクションを切断(F:\Videos\niconico\system\library.db)

20210321105156:データベースへコネクションを確立(F:\Videos\niconico\system\library.db):true

20210321105156:マイリスト一覧の読み込み完了:F:\Videos\niconico\system\myLists.xml

20210321105156:検索条件の読み込み完了:F:\Videos\niconico\system\searchItems.xml

20210321105156:ダウンロードリストを読み込み:F:\Videos\niconico\system\downloadList.xml

20210321105156:ダウンロードリストを保存:F:\Videos\niconico\system\downloadList.xml

20210321105156:履歴の読み込みを開始:F:\Videos\niconico\system\history.xml

20210321105156:履歴の読み込み完了

20210321105156:バージョンチェック(currentVersion:4.0.1)

20210321105157:ログイン成功:[Event type="LoginSuccess" bubbles=false cancelable=false eventPhase=2]

20210321105157:マイリスト更新即時実行

20210321105157:マイリスト更新のスケジュール実行完了

20210321105157:マイリスト更新のスケジュール実行完了

20210321105157:ログイン:[HTTPStatusEvent type="onFirestTimeLoginSuccess" bubbles=false cancelable=false eventPhase=2 status=0 redirected=false responseURL=null]
```

**Comment by SSW-SCIENTIFIC** [comment]
It looks problem that

```xml
<windowPosition_x>-32000</windowPosition_x>
<windowPosition_y>-32000</windowPosition_y>
```

these variables are too large as absolute to open window in visible zone of desktop.
If you want to reuse config.xml, you change these variables into values of `playerWindowPosition`.
