### ISSUE TITLE
動画のサイズが正しくない場合があります (2.7.1-beta)

### ISSUE THREAD

**Issue by tamo** [SSW-SCIENTIFIC/NNDD#5]
時々「サイズが正しくない」と言われます。
例えばこの動画は、非エコノミーでもエコノミーでも、サイズがエラーになります。

    20180805183725:		CreateDmcSessionSuccess:so33624181:巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181]
    20180805183725:	拡張子を判定:videoType=VIDEO_TYPE_MP4, 拡張子=.mp4
    20180805183725:	保存ファイル名:巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181].mp4
    20180805183725:	ニコ動の動画タイトル:巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181].mp4
    20180805183727:	動画のDLを開始:DL先=http://pa11718e501.dmc.nico/vod/ht2_nicovideo/nicovideo-so33624181_fac0bda42af204aa9adc7d8abb40ff92adeedd191219384f64e3fe37039e855d?ht2_nicovideo=2424211.wkhwfk_pczeqf_1l0wucxzpxaem
    20180805183727:	VideoGetStart:so33624181
    20180805183727:	動画取得中...:VideoGetStart
    20180805183728:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://pa11718e501.dmc.nico/vod/ht2_nicovideo/nicovideo-so33624181_fac0bda42af204aa9adc7d8abb40ff92adeedd191219384f64e3fe37039e855d?ht2_nicovideo=2424211.wkhwfk_pczeqf_1l0wucxzpxaem"]
    20180805183728:			Content-Length:310882822
    20180805183915:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805184103:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805184251:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805184439:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805184627:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805184815:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805185003:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805185151:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805185339:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805185527:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805185716:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805185904:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805190051:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805190240:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805190428:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805190616:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805190804:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805190952:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805191140:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805191328:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805191516:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/wkhwfken9o8ftigb6y563d7x9oy7v2qwvhcudyvmr3vklktlxl-4049242834315c372b54?_format=json&_method=PUT"]
    20180805191622:	ダウンロードした動画のサイズが正しくない:実際のサイズ=310882068, 想定されたサイズ=310882822
    20180805191622:	動画取得失敗:VideoGetFail:DownloadFail
    20180805191622:	エラー:巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181].mp4
    20180805191622:	***動画取得エラー終了***

**Comment by SSW-SCIENTIFIC** [comment]
こちらの手元では, 上記の動画はプレミアムアカウント, 非プレミアムアカウント共にダウンロードは正常に完了し, 再現しませんでした(非プレミアムではエコノミーモード)。

宜しければ通信環境, OS, アカウントの大まかな情報(プレミアム/非プレミアム等), ダウンロード失敗と判断された動画ファイルをお送りいただけますか？
但し動画ファイルについてはサイズが大きいこと, そして著作権上公開とすることは問題がありますので, 上手い方法を取っていただく必要があるかと思います。

簡単なものであればアップローダにアップしてダウンロード用のパスワードを(リポジトリを見れば私のメールアドレスは分かるかと思いますので)お送り頂くのがひとつ挙げられます。
少々手が込むものですと, ここに私の公開鍵を添付しますので, それで動画ファイルを暗号化して公然とアップロードして頂く, ということも可能です。

何れにせよ現状だと何とも言えない状態なので, とりあえずはダウンロードされたものの中身を(バイナリエディタ等で)見てみるのが手っ取り早いかと思います。

[public.zip](https://github.com/SSW-SCIENTIFIC/NNDD/files/2260521/public.zip)

**Comment by SSW-SCIENTIFIC** [comment]
お送りいただいたファイルですが, 何か復号後のサイズがジャスト 100,000,000 bytes なんですけれども, これで間違いないですか？
一応, MP4としては正常で, 途中(恐らくダウンロードされたところ)まではプレイヤーでの再生も可能でしたが・・・・・
暗号化された状態でのチェックサム(sha256sum)は下記の通りでした。

`97bb18797f1ff3916c66ba856820c98758317903ed6bebeda5ac0442bc7ab3b4`

上記のログを見る限り, 動画サイズは 296MiB 程度で, かつ全体の 99.99976% はダウンロードされているため, 私としてはそのぐらいのファイルサイズを想定していたのですが・・・・

**Comment by SSW-SCIENTIFIC** [comment]
あと, 可能であればディスク使用率のご確認, 有線接続の場合に同様の問題が起こるかどうかをご確認頂けると有り難いです。

**Comment by tamo** [comment]
そう言われてみればログと合いませんね。たしかに不思議です。
でも手元にあるのは
100,000,000 バイト (エコノミー) と
960,237,124 バイト (非エコノミー) みたいです。
SHA256 ハッシュ値も合っています。

ディスクは、あと400GB ほど残っています。
両方をそれぞれ 2回ダウンロードしたのですが、サイズは 2回とも同じになっているようです。

有線にするのは少し時間がかかりますので、のちほどトライします。

まずは非エコノミーの方を同様にお送りしますね。
7089094185129 で、パスワードは同じです。

なにか設定ファイルが悪い可能性はありますか？
書き忘れていましたが、MineAP さんの 2.4.3 から、いきなり 2.7.1-beta に設定を引きついで使っています。
一度消して真っ白な状態からやり直したほうが良ければ、そうしてみます。

何か変なので、マシンを再起動したり、他にもいろいろ試してみたいと思います。

**Comment by SSW-SCIENTIFIC** [comment]
非エコノミーの方を見てみましたが, ダウンロード成功のものと比較して, 純粋に末尾 972 bytes の欠落でした(先頭から欠落部分手前まで完全一致)。

v2.4.3からv2.7.1-Betaへのアップデートで最も大きく異なるのは, DMCサーバからダウンロード可能な場合は必ずDMCサーバ(dmc.nico)からダウンロードすることです。
DMCサーバは配信されるファイルサイズが大きくなったにも拘らず, 通信速度制限が旧来のSmileサーバと比較して強烈にかかっており, 通信環境の安定した状況でも ～500KiB/s 程度しか出ません。
このことは取りも直さずダウンロードにかかる時間が大幅に伸びていることを意味します。
即ち相対的に通信状況が不安定になりがちな無線LAN接続で(特にサイズの大きな)動画のダウンロードを行う場合, 予期しない通信切断が発生しやすくなると思われます(それでもプロトコルレベルでエラー検出や再送要求は行われているはずです)。
そのため, 途中までダウンロードされた状態で通信切断となると, このような末尾の欠落したファイルが生成され得るとは予想されます。


とりあえずは有線で様子を見て頂く必要はあろうかと思います。
NNDD側で可能な対応は, サイズ不足の動画に対してレジューム(サーバ側は対応)し, 不足しているデータの再送要求を明示的に送信することになろうかと思います。

これについては対応検討とさせてください。

**Comment by tamo** [comment]
末尾だけの欠けであれば、バグというよりも環境っぽいですね。
おっしゃるとおりの対応で納得です。
数日中に有線で試してみて、結果を追記したいと思いますが、いずれにせよ close していただいて構いません。
ここまでの調査、ありがとうございます!

**Comment by SSW-SCIENTIFIC** [comment]
よくよく振り返ると, (ダウンロードではなくストリーミング再生ですが)動画末尾まで再生されないケースが私の環境でも発生していることに思い当たりました。
大抵リロードすると末尾まで再生出来るのであまり気にしていませんでしたが, 上記ケースと同じように思えます。

5chのツールスレやnFinderスレ等でも末尾までダウンロードが完了しないケースがしばしば報告されているため, やはり通信速度制限の厳しいDMCサーバからダウンロード/ストリーミングする際に(通信に掛かる時間が大きくなることで)発生しやすいのかなと思います。

/*
  余談ですが, NNDDはストリーミング再生しているといいつつ実際にはプログレッシブ再生をしています
  つまりローカルファイルに順次追記しながら再生を実行しているので, 本来のストリーミングであれば起こりにくい本件と同じ現象が発生します
*/

**Comment by SSW-SCIENTIFIC** [comment]
とりあえず[v2.8.2-Alpha][]でレジュームに対応してみました。
ダウンロード完了時にContent-Lengthよりダウンロードサイズが小さい場合に自動レジュームします。

但し, プレミアムアカウントでしか試していないので, 非プレミアムアカウントや非ログインユーザの場合にどうなるのか要確認です。
DMCセッションのタイムアウトで状況は再現可能なのですが, デバッガなしだと少々面倒です。

[v2.8.2-Alpha]: https://github.com/SSW-SCIENTIFIC/NNDD/releases/tag/v2.8.2-Alpha

**Comment by tamo** [comment]
2.8.2 でレジュームにより正しく取得できることを確認しました。
ちゃんと status 206 が返っています。ありがとうございます。
レジュームして完成したファイルの SHA256 は E1556F0CB1A874B8E8E573836B3AF08DD8A2B614A49A659DF2A7E3B34154CEF3 です。(手打ちなので少し間違っているかもしれません)
お手元のファイルと同じでしょうか？

なお、ログを見ると、レジュームはサムネ、コメ、市場まで取り直しているみたいです。
動画だけでもいいかもしれないですね。

    20180809140147:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/oac372jfl3yw056xavuau11foxbjqz6539qkjlli98yvx0dwi9-4048242834315c372b54?_format=json&_method=PUT"]
    20180809140335:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/oac372jfl3yw056xavuau11foxbjqz6539qkjlli98yvx0dwi9-4048242834315c372b54?_format=json&_method=PUT"]
    20180809140523:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/oac372jfl3yw056xavuau11foxbjqz6539qkjlli98yvx0dwi9-4048242834315c372b54?_format=json&_method=PUT"]
    20180809140711:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://api.dmc.nico/api/sessions/oac372jfl3yw056xavuau11foxbjqz6539qkjlli98yvx0dwi9-4048242834315c372b54?_format=json&_method=PUT"]
    20180809140838:	ダウンロードした動画のサイズが正しくない:実際のサイズ=960237124, 想定されたサイズ=960238096
    20180809140838:	レジューム開始: 開始位置=960237124, リトライ回数=1
    20180809140838:	WatchStart:so33624181
    20180809140838:	動画ページにアクセス中...:WatchStart
    20180809140839:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://www.nicovideo.jp/watch/so33624181"]
    20180809140839:		WatchSuccess:so33624181:巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181]
    20180809140839:	動画ページアクセス成功:WatchSuccess
    20180809140839:	ThumbInfoGetStart:so33624181
    20180809140839:	サムネイル情報取得中...:ThumbInfoGetStart
    20180809140839:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://ext.nicovideo.jp/api/getthumbinfo/so33624181"]
    20180809140840:		ThumbInfoGetSuccess:C:\Users\tamo\Documents\NNDD\Download\巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181][ThumbInfo].xml
    20180809140840:	サムネイル情報取得成功:ThumbInfoGetSuccess
    20180809140840:	ThumbImgGetStart:so33624181
    20180809140840:	サムネイル画像取得中...:ThumbImgGetStart
    20180809140840:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://tn.smilevideo.jp/smile?i=33624181"]
    20180809140840:		ThumbImgGetSuccess:C:\Users\tamo\Documents\NNDD\Download\巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181][ThumbImg].jpeg
    20180809140840:	サムネイル画像取得成功:ThumbImgGetSuccess
    20180809140840:	GetFlvAccessStart:so33624181(so33624181)
    20180809140840:	動画取得APIにアクセス中...:GetFlvAccessStart
    20180809140840:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://flapi.nicovideo.jp/api/getflv/so33624181?"]
    20180809140840:		GetFlvAccessSuccess:so33624181:巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181]
    20180809140840:	APIアクセス成功:GetFlvAccessSuccess
    20180809140840:	CommentGetStart:so33624181
    20180809140840:	コメント取得中...:CommentGetStart
    20180809140840:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://nmsg.nicovideo.jp/api/"]
    20180809140841:		CommentGetSuccess:C:\Users\tamo\Documents\NNDD\Download\巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181].xml
    20180809140841:	コメント取得成功:CommentGetSuccess
    20180809140841:	OwnerCommentGetStart:so33624181
    20180809140841:	投稿者コメント取得中...:OwnerCommentGetStart
    20180809140841:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://nmsg.nicovideo.jp/api/"]
    20180809140841:		OwnerCommentGetSuccess:C:\Users\tamo\Documents\NNDD\Download\巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181][Owner].xml
    20180809140841:	投稿者コメント取得成功:OwnerCommentGetSuccess
    20180809140841:	IchibaInfoGetStart:so33624181
    20180809140841:	市場情報取得中...:IchibaInfoGetStart
    20180809140841:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="http://ichiba.nicovideo.jp/embed/?action=showMain&v=so33624181&rev=20100805"]
    20180809140841:		IchibaInfoGetSuccess:C:\Users\tamo\Documents\NNDD\Download\巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181][IchibaInfo].html
    20180809140841:	市場情報取得成功:IchibaInfoGetSuccess
    20180809140841:	CreateDmcSessionStart:1533202444(so33624181)
    20180809140841:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=201 redirected=false responseURL="http://api.dmc.nico/api/sessions/?_format=json"]
    20180809140841:		CreateDmcSessionSuccess:so33624181:巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181]
    20180809140841:	拡張子を判定:videoType=VIDEO_TYPE_MP4, 拡張子=.mp4
    20180809140841:	保存ファイル名:巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181].mp4
    20180809140841:	ニコ動の動画タイトル:巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181].mp4
    20180809140841:	動画のDLを開始:DL先=http://pa11718e501.dmc.nico/vod/ht2_nicovideo/nicovideo-so33624181_6fb4e84c490aab9f3027bc6a1cb13cdac843f294fe37cedec9f349160cbce55f?ht2_nicovideo=2424211.08qdef_pd6gyi_235lijs8vrkiz
    20180809140841:	VideoGetStart:so33624181
    20180809140841:	動画取得中...:VideoGetStart
    20180809140841:			httpResponseStatus:[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=206 redirected=false responseURL="http://pa11718e501.dmc.nico/vod/ht2_nicovideo/nicovideo-so33624181_6fb4e84c490aab9f3027bc6a1cb13cdac843f294fe37cedec9f349160cbce55f?ht2_nicovideo=2424211.08qdef_pd6gyi_235lijs8vrkiz"]
    20180809140841:			Content-Length:960238096
    20180809140842:		VideoGetSuccess:C:\Users\tamo\Documents\NNDD\Download\巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181].mp4
    20180809140842:	動画取得成功:VideoGetSuccess
    20180809140842:	動画のダウンロード完了:file:///C:/Users/tamo/Documents/NNDD/Download/巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181].mp4
    20180809140842:	***動画取得完了***

ご丁寧に対応いただき、ありがとうございます。

**Comment by SSW-SCIENTIFIC** [comment]
手元のファイルに対する`shasum -a 256`の結果は下記のようになっていますので一致しています。

```
e1556f0cb1a874b8e8e573836b3af08dd8a2b614a49a659df2a7e3b34154cef3  巽悠衣子の「下も向いて歩こう＼(^o^)／」 第55回放送（2018.07.27） - [so33624181].mp4
```

レジューム時の動画以外の取得については回避するのが面倒なので通常の動画取得フローと同じ流れになっています。
気が向いたら直すかもしれません。

**Comment by tamo** [comment]
完璧ですね！ 完全に了解しました。
